Repository csivitu/vbay, pull requests merged in 2022-10, with the labels that each got.

#27 aligned centrally
  index.css
Labels: hacktoberfestapproved

#29 fix: Background image issue resolved on all pages
  cart.html
  index.html
  products.html
  review.html
Labels: hacktoberfestapproved

#34 Feat:scroll issue
  products.css
Labels: hacktoberfestapproved

#31 Scroll bar customization
  cart.css
  index.css
  products.css
  review.css
Labels: hacktoberfestapproved

#38 Product Updated
  products.css
Labels: hacktoberfestapproved

#44 #40
  products.css
  products.html
Labels: hacktoberfestapproved

#49 Adding darkModeFunction()
  index.css
  index.html
  index.js
Labels: hacktoberfestapproved

#52 [BUG] Structure files #4
  allcss/cart.css
  allcss/index.css
  allcss/products.css
  allcss/review.css
  allhtml/allcsscart.html
  allhtml/index.html
  allhtml/products.html
  allhtml/review.html
Labels: hacktoberfestapproved

#60 doc: adding love
  README.md
Labels: hacktoberfestapproved

#79 Enhance: Arrange cart page
  CSS/cart.css
  HTML/cart.html
Labels: hacktoberfest-approved

#82 feat : updated the readme
  README.md
Labels: hacktoberfest

#93 refact: restructured folder structure to accomodate backend
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/Components/Cart.js
  frontend/src/Components/Header.js
  frontend/src/Components/Home.js
  frontend/src/Components/Products.js
  frontend/src/Components/Review.js
  frontend/src/Styles/App.css
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: hacktoberfest-approved
